# Generated by Django 4.2.2 on 2023-07-16 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0003_meep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meep',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
